"""event table

Revision ID: 8815df6641f8
Revises: 0e87f252542e
Create Date: 2020-02-03 12:32:04.691712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8815df6641f8'
down_revision = '0e87f252542e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('event_owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_date_start'), 'event', ['date_start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_date_start'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
