"""relations table

Revision ID: dbf9147e5f70
Revises: 8815df6641f8
Create Date: 2020-02-05 00:44:14.235685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf9147e5f70'
down_revision = '8815df6641f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1', sa.Integer(), nullable=True),
    sa.Column('user2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_users')
    # ### end Alembic commands ###
